language: python
python: 3.5
before_install:
- chmod 400 deploy_key
- git clone --branch=master https://github.com/FatConan/sand.git sand-processor
- cd sand-processor
- pip install -r requirements.txt
script:
- cd $TRAVIS_BUILD_DIR
- python sand-processor/sand.py .
deploy:
  provider: script
  skip_cleanup: true
  script: bash $TRAVIS_BUILD_DIR/deploy.sh
  on:
    branch: master
env:
  global: 
dd:
- openssl aes-256-cbc -K $encrypted_1f9732908fdf_key -iv $encrypted_1f9732908fdf_iv
  -in deploy_key.enc -out deploy_key -d
